# Generated by Django 5.0.6 on 2024-06-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='store_categ_name_1278fd_idx',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['id', 'name'], name='store_categ_id_db4281_idx'),
        ),
    ]
