# Generated by Django 5.0.6 on 2024-06-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_category_store_categ_name_1278fd_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
