# Generated by Django 5.0.6 on 2024-06-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_available_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='store_categ_id_db4281_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_id_2abda1_idx',
        ),
    ]
