# Generated by Django 5.0.6 on 2024-06-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_options_rename_name_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
