# Generated by Django 5.0.6 on 2024-06-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_createdat_customuser_updateat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='updateAt',
        ),
        migrations.AddField(
            model_name='customuser',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
